name: inspect-excel

on:
  workflow_dispatch:
    inputs:
      public_link:
        description: 'Public Yandex Disk link to .xlsm'
        required: true
        default: 'https://disk.360.yandex.ru/d/6jTrW5_ebpHfKQ'

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Download file from Yandex Disk
        env:
          PUBLIC_LINK: ${{ github.event.inputs.public_link }}
        run: |
          mkdir -p data
          echo "Requesting download href for: $PUBLIC_LINK"
          HREF=$(curl -sG --data-urlencode "public_key=$PUBLIC_LINK" "https://cloud-api.yandex.net/v1/disk/public/resources/download" | python - << 'PY'
import sys, json
data = json.load(sys.stdin)
print(data.get("href",""))
PY
)
          if [ -z "$HREF" ]; then
            echo "Failed to obtain direct download link. Is the link public (no login required)?"
            exit 1
          fi
          echo "Direct href obtained."
          curl -L "$HREF" -o data/report.xlsm
          ls -l data

      - name: Inspect excel
        run: |
          python inspect_excel.py data/report.xlsm | tee inspect_output.txt

      - name: Upload inspection result
        uses: actions/upload-artifact@v4
        with:
          name: excel-inspection
          path: inspect_output.txt
